import {
    PropulsionType,
    Ride,
    RideStatus,
    VehicleCategory,
    VehicleCondition,
} from "../../types";

export const mockRides: Ride[] = [
  {
    id: "ride-001",
    vehicle: {
      id: "BK-4821",
      plateNumber: "LG-481-BK",
      category: VehicleCategory.Bike,
      make: "Trek",
      model: "FX 3",
      year: 2023,
      colour: "Matte Black",
      propulsion: PropulsionType.HumanPowered,
      condition: VehicleCondition.Excellent,
      seatingCapacity: 1,
      rangeKm: 0,
      topSpeedKmh: 30,
      features: ["lightweight-frame", "disc-brakes", "ergonomic-saddle"],
      imageUrl:
        "https://dummyjson.com/image/128x128/1a1a1a/1DB954?type=png&text=Bike",
      rating: 4.8,
      totalRatings: 312,
    },
    driver: {
      name: "Self-ride",
      avatarUrl: "https://dummyjson.com/icon/emilys/128",
      rating: 0,
      totalTrips: 0,
    },
    etaMinutes: 2,
    durationMinutes: 12,
    priceNgn: 2500,
    co2SavedKg: 1.8,
    co2ComparisonLabel: "Equal to charging 150 phones",
    status: RideStatus.Available,
    destination: {
      latitude: 6.5244,
      longitude: 3.3792,
      label: "Lagos Island",
      address: "10 Broad Street, Lagos Island, Lagos",
      distanceKm: 3.2,
    },
    tags: ["eco", "fastest", "no-emissions"],
  },
  {
    id: "ride-002",
    vehicle: {
      id: "SC-2047",
      plateNumber: "LG-204-SC",
      category: VehicleCategory.Scooter,
      make: "Yadea",
      model: "G5",
      year: 2024,
      colour: "Pearl White",
      propulsion: PropulsionType.Electric,
      condition: VehicleCondition.Excellent,
      seatingCapacity: 2,
      rangeKm: 120,
      topSpeedKmh: 55,
      features: [
        "led-lights",
        "usb-charging",
        "anti-theft-alarm",
        "regenerative-braking",
      ],
      imageUrl:
        "https://dummyjson.com/image/128x128/1a1a1a/1DB954?type=png&text=Scooter",
      rating: 4.6,
      totalRatings: 198,
    },
    driver: {
      name: "Self-ride",
      avatarUrl: "https://dummyjson.com/icon/emilys/128",
      rating: 0,
      totalTrips: 0,
    },
    etaMinutes: 4,
    durationMinutes: 18,
    priceNgn: 5200,
    co2SavedKg: 2.4,
    co2ComparisonLabel: "Saves a 5km car trip worth of emissions",
    status: RideStatus.Available,
    destination: {
      latitude: 6.4281,
      longitude: 3.4219,
      label: "Victoria Island",
      address: "Plot 1649 Adeola Hopewell St, Victoria Island, Lagos",
      distanceKm: 5.7,
    },
    tags: ["eco", "popular", "low-emissions"],
  },
  {
    id: "ride-003",
    vehicle: {
      id: "EV-9913",
      plateNumber: "LG-991-EV",
      category: VehicleCategory.Car,
      make: "BYD",
      model: "Atto 3",
      year: 2024,
      colour: "Cosmos Black",
      propulsion: PropulsionType.Electric,
      condition: VehicleCondition.Excellent,
      seatingCapacity: 5,
      rangeKm: 420,
      topSpeedKmh: 160,
      features: [
        "ac",
        "360-camera",
        "wireless-charging",
        "sunroof",
        "heated-seats",
      ],
      imageUrl:
        "https://dummyjson.com/image/128x128/1a1a1a/1DB954?type=png&text=Car",
      rating: 4.9,
      totalRatings: 541,
    },
    driver: {
      name: "Chidi Okafor",
      avatarUrl: "https://dummyjson.com/icon/michaelw/128",
      rating: 4.95,
      totalTrips: 1204,
    },
    etaMinutes: 6,
    durationMinutes: 22,
    priceNgn: 11200,
    co2SavedKg: 3.1,
    co2ComparisonLabel: "Equivalent to planting 0.3 trees today",
    status: RideStatus.Available,
    destination: {
      latitude: 6.6018,
      longitude: 3.3515,
      label: "Ikeja",
      address: "15 Allen Avenue, Ikeja, Lagos",
      distanceKm: 9.4,
    },
    tags: ["electric", "premium", "ac", "low-emissions"],
  },
  {
    id: "ride-004",
    vehicle: {
      id: "SC-3388",
      plateNumber: "LG-338-SC",
      category: VehicleCategory.Scooter,
      make: "NIU",
      model: "NQi GT",
      year: 2023,
      colour: "Midnight Blue",
      propulsion: PropulsionType.Electric,
      condition: VehicleCondition.Good,
      seatingCapacity: 2,
      rangeKm: 100,
      topSpeedKmh: 70,
      features: ["gps-tracking", "app-connected", "keyless-start"],
      imageUrl:
        "https://dummyjson.com/image/128x128/1a1a1a/1DB954?type=png&text=Scooter",
      rating: 4.5,
      totalRatings: 87,
    },
    driver: {
      name: "Self-ride",
      avatarUrl: "https://dummyjson.com/icon/emilys/128",
      rating: 0,
      totalTrips: 0,
    },
    etaMinutes: 3,
    durationMinutes: 14,
    priceNgn: 4400,
    co2SavedKg: 1.95,
    co2ComparisonLabel: "Saves the same CO₂ as skipping one beef meal",
    status: RideStatus.Available,
    destination: {
      latitude: 6.548,
      longitude: 3.3536,
      label: "Yaba",
      address: "22 Herbert Macaulay Way, Yaba, Lagos",
      distanceKm: 4.1,
    },
    tags: ["eco", "budget", "low-emissions"],
  },
  {
    id: "ride-005",
    vehicle: {
      id: "EV-0072",
      plateNumber: "LG-007-EV",
      category: VehicleCategory.Car,
      make: "Tesla",
      model: "Model 3",
      year: 2024,
      colour: "Pearl White Multi-Coat",
      propulsion: PropulsionType.Electric,
      condition: VehicleCondition.Excellent,
      seatingCapacity: 5,
      rangeKm: 576,
      topSpeedKmh: 225,
      features: [
        "autopilot",
        "ac",
        "premium-audio",
        "glass-roof",
        "over-the-air-updates",
      ],
      imageUrl:
        "https://dummyjson.com/image/128x128/1a1a1a/1DB954?type=png&text=Tesla",
      rating: 5.0,
      totalRatings: 204,
    },
    driver: {
      name: "Amara Nwosu",
      avatarUrl: "https://dummyjson.com/icon/sarahm/128",
      rating: 4.98,
      totalTrips: 876,
    },
    etaMinutes: 8,
    durationMinutes: 30,
    priceNgn: 18400,
    co2SavedKg: 4.7,
    co2ComparisonLabel: "Offsets a 30-minute petrol car journey",
    status: RideStatus.Available,
    destination: {
      latitude: 6.4698,
      longitude: 3.5852,
      label: "Lekki Phase 1",
      address: "5 Admiralty Way, Lekki Phase 1, Lagos",
      distanceKm: 14.2,
    },
    tags: ["electric", "premium", "long-range", "ac"],
  },
  {
    id: "ride-006",
    vehicle: {
      id: "BK-7734",
      plateNumber: "LG-773-BK",
      category: VehicleCategory.Bike,
      make: "Giant",
      model: "Escape 3",
      year: 2022,
      colour: "Charcoal Grey",
      propulsion: PropulsionType.HumanPowered,
      condition: VehicleCondition.Good,
      seatingCapacity: 1,
      rangeKm: 0,
      topSpeedKmh: 25,
      features: [
        "lightweight-frame",
        "flat-handlebars",
        "puncture-resistant-tyres",
      ],
      imageUrl:
        "https://dummyjson.com/image/128x128/1a1a1a/1DB954?type=png&text=Bike",
      rating: 4.7,
      totalRatings: 430,
    },
    driver: {
      name: "Self-ride",
      avatarUrl: "https://dummyjson.com/icon/emilys/128",
      rating: 0,
      totalTrips: 0,
    },
    etaMinutes: 1,
    durationMinutes: 8,
    priceNgn: 1500,
    co2SavedKg: 0.95,
    co2ComparisonLabel: "Zero emissions — pure pedal power",
    status: RideStatus.Available,
    destination: {
      latitude: 6.5158,
      longitude: 3.3898,
      label: "Surulere",
      address: "7 Adeniran Ogunsanya St, Surulere, Lagos",
      distanceKm: 1.8,
    },
    tags: ["zero-emissions", "cheapest", "short-trip"],
  },
];
